// Constantes
export const ADD_BOOK = 'ADD_BOOK';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_ERROR = 'ADD_BOOK_ERROR';

export const START_DOWNLOAD_BOOKS = 'START_DOWNLOAD_BOOKS';
export const DOWNLOAD_BOOKS_SUCCESS = 'DOWNLOAD_BOOKS_SUCCESS';
export const DOWNLOAD_BOOKS_ERROR = 'DOWNLOAD_BOOKS_ERROR';

export const GET_BOOK_DELETE = 'GET_BOOK_DELETE';
export const GET_BOOK_DELETE_SUCCESS = 'GET_BOOK_DELETE_SUCCESS';
export const GET_BOOK_DELETE_ERROR = 'GET_BOOK_DELETE_ERROR';

export const GET_BOOK_EDIT = 'GET_BOOK_EDIT';
export const STAR_EDIT_BOOK = 'STAR_EDIT_BOOK';
export const GET_BOOK_EDIT_SUCCESS = 'GET_BOOK_EDIT_SUCCESS';
export const GET_BOOK_EDIT_ERROR = 'GET_BOOK_EDIT_ERROR';

// Rutas
export const BOOKS_ROUTE = '/books';